image: python:latest
  
before_script:
  - python -V
  - git clone --depth 1 https://gitlab.com/kicad/libraries/kicad-library-utils $CI_BUILDS_DIR/kicad-library-utils

footprints:
  only:
    refs:
      - merge_requests
    changes:
      - "**/*.step"
      - "**/*.wrl"
  script:
    - $CI_BUILDS_DIR/kicad-library-utils/klc-check/gitlabci/check_packages3d.sh
  artifacts:
    reports:
      metrics: metrics.txt
